name: 'sigesawordpress'

services:
  servicio1:
    image: mysql:8.0
    container_name: contenedorsigesawordpress
    ports:
      - "${PUERTO_EXTERNO_CONTENEDOR_MYSQL}:3307" # Mapea el puerto 3307 del host al 3307 del contenedor (lo toma de .env)
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD_MYSQL} # lo toma del archivo .env
      MYSQL_DATABASE: ${BASE_DE_DATOS} # # lo toma del archivo .env
    # volumes:
      # - db_data:/var/lib/mysql # Persistencia de datos

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: mi-phpmyadmin
    ports:
      - "8081:80" # Mapea el puerto 8081 del host al 80 del contenedor
    environment:
      PMA_HOST: servicio1 # El nombre del servicio de la base de datos en Docker Compose
    depends_on:
      - servicio1

# volumes:
  # db_data: