name: 'unitylab'

services:
  serviciomysql:
    image: mysql:latest
    container_name: contenedorserviciomysql
    ports:
      - "${PUERTO_EXTERNO_CONTENEDOR_MYSQL}:3306" # Mapea el puerto host al puerto del contenedor (lo toma de .env)
    environment:
      MYSQL_USER: ${OTRO_USUARIO_ROOT}
      MYSQL_PASSWORD: ${OTRO_USUARIO_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD_MYSQL} # lo toma del archivo .env
      MYSQL_DATABASE: ${BASE_DE_DATOS} # # lo toma del archivo .env
    volumes:
      # 1. Persistencia de Datos
      - db_data:/var/lib/mysql
      # 2. Carga Automática del SQL
      - ./backup_DB:/docker-entrypoint-initdb.d
  serviciophpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: contenedorserviciophpmyadmin
    ports:
      - "${PUERTOEXTERNO_PHPMYADMIN}:80" # Mapea el puerto 8081 del host al 80 del contenedor
    environment:
      PMA_HOST: serviciomysql # El nombre del servicio de la base de datos en Docker Compose
    depends_on:
      - serviciomysql 

volumes:
  db_data: