name: 'unitylabconfiguraciones'

services:
  servicio1:
    image: mysql:8.0
    container_name: contenedormysql
    ports:
      - "${PUERTO_EXTERNO_CONTENEDOR_MYSQL}:3306" # Mapea el puerto host al puerto del contenedor (lo toma de .env)
    environment:
      MYSQL_USER: fernando
      MYSQL_PASSWORD: ${OTRO_USUARIO_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD_MYSQL} # lo toma del archivo .env
      MYSQL_DATABASE: ${BASE_DE_DATOS} # # lo toma del archivo .env
    # volumes:
      # - db_data:/var/lib/mysql # Persistencia de datos

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: contenedorphpmyadmin
    ports:
      - "${PUERTOEXTERNO_PHPMYADMIN}:80" # Mapea el puerto 8081 del host al 80 del contenedor
    environment:
      PMA_HOST: servicio1 # El nombre del servicio de la base de datos en Docker Compose
    depends_on:
      - servicio1 

# volumes:
  # db_data: